### PR TITLE
Fix CI build

### PR DESCRIPTION
**Pull request by russkel**
Fixes Travis building and testing for Linux and OSX. I don't have any experience with appveyor or building this on Windows so I will leave it for someone else.

### CODE REVIEW

**Comment by russkel** [comment]
Ah, travis CI isn't activated for PRs. I'll get travis working on my own repository.

**Comment by msis** [comment]
Thanks Russ!

I'm not sure how to activate Travis for PRs, please advise.

**Comment by russkel** [comment]
No problem @msis. To activate travis for PRs, log onto to Travis, go to settings for the repository and then make sure "Build pushed PRs" is turned on:

image


Also: https://travis-ci.com/github/russkel/python-moos/jobs/319908963 these two tests are genuinely failing. Any idea why?

You also use your own branch of core-moos for CI, which we probably shouldn't need to do. Can we rebase that branch off the master core-moos and upstream the changes? It looks like mostly Appveyor mods, so I will change the travis one to use the official core-moos branch.

**Comment by russkel** [comment]
Another case of it happening here https://travis-ci.com/github/russkel/python-moos/jobs/320319760

**Comment by russkel** [comment]
Alright, done. This should be good to merge. Results can be seen here: https://travis-ci.com/github/russkel/python-moos

The failures are due to test failures, which was the point of this PR.

**Comment by msis** [comment]
> No problem @msis. To activate travis for PRs, log onto to Travis, go to settings for the repository and then make sure "Build pushed PRs" is turned on:
> 
> image
> 
> Also: https://travis-ci.com/github/russkel/python-moos/jobs/319908963 these two tests are genuinely failing. Any idea why?
> 
> You also use your own branch of core-moos for CI, which we probably shouldn't need to do. Can we rebase that branch off the master core-moos and upstream the changes? It looks like mostly Appveyor mods, so I will change the travis one to use the official core-moos branch.

That's what I have in the settings too.
I will go ahead and merge so we can check #3.

**Comment by russkel** [comment]
Hmm, okay there must be something I am missing. It looks like travis is building the PRs: https://travis-ci.org/github/msis/python-moos/pull_requests

I think there is an option in GitHub, I'll see if I can find it.

**Comment by russkel** [comment]
https://github.com/russkel/python-moos/pull/1

It's working on my repository. The only thing I can think of is due to the age of this repository maybe Travis CI does not have Github Apps integration: https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

Instructions on how to migrate are in that blog post.

**Pull request merged**
