### PR TITLE
Update pybind, fix deprecated calls

### PR DESCRIPTION
**Pull request by russkel**
Some colleagues are making use of python-moos so it only seemed fit to freshen it up and get it using the latest version of pybind11.

- Updates included pybind files
- Removes all deprecated warnings from Python
- Includes basic build instructions

### CODE REVIEW

**Comment by russkel** [comment]
Well that was pretty painless. Same test errors exist.

**Comment by russkel** [comment]
Hi @msis, any interest in merging this?

**Comment by msis** [comment]
Hi @russkel !

Thanks for all the changes. These are awesome.

I made a copy of `pybind` to follow the MOOS conventions.
However, here is my main motivations:
1. `pybind` is totally independent. If one day they decide to move out of github or change org/user/name, the submodule will fail.
2. you cannot tell git which tag to use. (It only support branches, luckily in this case `pybind` has branches frozen at the tags). As of now, if `v3` has breaking changes with `v2`, we will be in a bad place.

I propose either reverting back to including the library (maybe under a `3rd_party` directory) or at least defining a specific branch in the `.gitsubmodule`. 
If you go with the second option, the a `shallow = true` would be great.

*(Sorry for the late reply, forgot to comment on this before!)*

**Comment by russkel** [comment]
> * `pybind` is totally independent. If one day they decide to move out of github or change org/user/name, the submodule will fail.

This is true. Is this that much of a concern given that we can fix the submodule url or add the code explicitly at a later date?

> * you cannot tell git which tag to use. (It only support branches, luckily in this case `pybind` has branches frozen at the tags). As of now, if `v3` has breaking changes with `v2`, we will be in a bad place.

Please see this commit: https://github.com/msis/python-moos/pull/3/commits/9295be06444e52111a9c64c5e1cb877ba07416d5. It sets the submodule at a specific commit, so it pulls v2.5.0. I believe this solves this particular issue.

I can add `shallow = true` no problem. It's your repo, let me know which you prefer.

**Comment by msis** [comment]
> This is true. Is this that much of a concern given that we can fix the submodule url or add the code explicitly at a later date?
It happen to me a couple of times.
And it is not like we will be updating `pybind` that often.

I just personally see no benefit of adding the submodule versus adding in the source.
The former adds a step at a checkout and a (very thin) risk of having the repo changing at some point in the future.

**Comment by russkel** [comment]
Okay, I'll update with a new version of the library code.

**Comment by msis** [comment]
Hey @russkel!
Please let me know when it’s all set for a merge.
Thanks for your contribution.

**Comment by russkel** [comment]
Oops sorry, this fell by the wayside. Will get to it when I get a moment!

**Comment by russkel** [comment]
Okay @msis that should be good to go.

I don't really understand the test failures that are occurring, but they are unrelated to this. Do you have any idea on those?

**Comment by russkel** [comment]
Whenever you're ready @msis ;)

**Comment by msis** [comment]
Thanks Russ!
I will try to figure out the reason behind those failing tests... (interestingly enough, one passes...)

**Comment by russkel** [comment]
@msis I did notice that some sometimes pass/fail depending on the order the CI stuff comes up. Could it be that it's trying to start multiple servers on the same machine?

**Pull request merged**
